services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - mural-mcp-portal

  mural-mcp-portal:
    build: ./
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      LOCALSTACK_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
    volumes:
      - ./src:/home/node/src
    networks:
      - mural-mcp-portal

networks:
  mural-mcp-portal:
    driver: bridge
